# Generated by Django 4.0.1 on 2022-01-14 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='likes_for_users',
            field=models.ManyToManyField(blank=True, related_name='likes_from', to=settings.AUTH_USER_MODEL,
                                         verbose_name='Лайки пользователям'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='likes_from_users',
            field=models.ManyToManyField(blank=True, related_name='likes_for', to=settings.AUTH_USER_MODEL,
                                         verbose_name='Лайки от пользователей'),
        ),
    ]
