# Generated by Django 4.0.1 on 2022-01-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_rename_male_customuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
